### ISSUE TITLE
overwrites paste register

### ISSUE THREAD

**Issue by jgallen23** [tpope/vim-vinegar#10]
if I yank some piece of text `yy` and then go into vinegar, select a file and then put `p`, it pastes `../` instead of the piece of text I yanked.

**Comment by CrashyBang** [comment]
Hey sorry this was the only reference to this issue I could find has anybody found a work around?

**Comment by CrashyBang** [comment]
Okay after some very extensive research there are a couple of things that do this:

FYI I am using neovim **NOT** vim.

- vim-vinegar
- set hidden
- set clipboard=unnamed (https://github.com/kien/ctrlp.vim/issues/648) (although I did not experience this)

Any thoughts?

**Comment by serebrov** [comment]
@CrashyBang I use neovim and I don't have this problem even with "set hidden" and "set clipboard=unnamed". So I guess the problem requires more research to find the exact reason it happens. Probably it is some of the plugins you have.

**Comment by CrashyBang** [comment]
@serebrov, have tried with minimal `init.vim` just using `vinegar` and was able to reproduce could be neovim version.

**Comment by dhleong** [comment]
I get this also in vim8, with just vinegar and no other plugins. I did some digging and found that if I comment out these lines:

```
let g:netrw_list_hide =
      \ join(map(split(&wildignore, ','), '"^".' . s:escape . '. "/\\=$"'), ',') . ',^\.\.\=/\=$' .
      \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles)-1:-1] ==# s:dotfiles ? ','.s:dotfiles : '')
if !exists("g:netrw_banner")
  let g:netrw_banner = 0
endif
```

pasting works as expected. This seems like a netrw bug, so I went ahead and reached out to Dr Chip. Will update if I find anything out

**Comment by city41** [comment]
I am experiencing this as well, using latest neovim (unstable master). What is strange is it only started happening recently, but netrw has not been updated since 2014. Is it possible some change in vim8 and neovim exposed this issue?

**Comment by mjackson** [comment]
For folks looking for a workaround, it looks like netrw corrupts the system clipboard register, but you can still use your own register instead as a workaround. e.g. instead of `yy` use `"ky` to store the result of the yank operation in register `"k`. Then, use `"kp` to paste from that register into your other buffer.

Like @city41, this wasn't a problem for me until recently.

**Comment by city41** [comment]
This issue has been fixed in vim8, they upgraded to netrw v167.

The issue still persists in neovim, and is being tracked in the linked issue just above. I believe neovim needs to also upgrade to netrw v167.

For now, I am switching to vim8.

**Comment by jsbarrett** [comment]
So not really a good solution (not generally applicable),
but I changed a line in vinegar.vim to fix this issue for myself.
(leaving here in case it helps anyone else)

From: `nnoremap <silent> <Plug>VinegarUp :call <SID>opendir('edit')<CR>`
To: `nnoremap <silent> <Plug>VinegarUp :let @p=@0<CR>:call <SID>opendir('edit')<CR>:let @*=@p<CR>`

This seems to have fixed the problem for me.
I have the clipboard hooked up as my default register
and pretty much only use that register in my personal workflow.
I only had the issue if my yanked text had an apostrophe in it,
and after updating the line in vinegar.vim to above I no longer have this issue.
This works for me because I know I never yank into any other registers,
so blowing away the p register in order to restore my * register is just fine for me.

**Comment by narajaon** [comment]
Using neovim and vinegar... This is actually really annoying
