### ISSUE TITLE
Future plans for git support?

### ISSUE THREAD

**Issue by andykais** [tpope/vim-vinegar#82]
The one thing holding me back from removing NERDTree is the [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin). There just isnt a similar version for netrw. The only option I can think of to get a quick view of my projects' files' status inside vim is with vim-fugitive, running `:Git status` which is still is more information than I want for the CWD. Is there any plans to add `git` support here or make another netrw plugin?

In case the answer is a definite no, how do you get this info for yourself using only netrw?

**Comment by neilvyas** [comment]
weighing in: I don't much care for something like `nerdtree-git`, but I would like the (hopefully simple to add) feature that netrw file deletions and movements are switched to the appropriate fugitive commands when in a git repo and when fugitive is installed.

**Comment by tpope** [comment]
I mostly just use `:Gstatus`. While I can appreciate that vinegar git support would be convenient, I don't really relate to the "too much information" argument. Maybe that's just because I favor small commits.

**Comment by Nekketsu** [comment]
+1
I think this is a very convenient feature!

**Comment by tpope** [comment]
I'm not sure why I left this open because netrw is not extensible. All we can do really is tweak options. We could do the `.gitignore` thing, as that is controlled by `g:netrw_list_hide`, but I'm not convinced it's a great idea, at least not for everyone, as `.gitignore` can contain things like configuration files that you _do_ want to see. Plus we're already using `'wildignore'` for that.
